test:
  demo: aaa
sso:
  login_url: http://sso-service/toLogin?redirect_url=
  auth_url: http://sso-service/login/authentication?token=

#注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://tu:8761/eureka
  healthcheck:
    enabled: true
    registry-fetch-interval-seconds: 10000 #间隔多久去拉取服务注册信息，默认为30秒

