test:
  demo: ccc
sso:
  login_url: http://tu/toLogin?redirect_url=
  auth_url: http://service-sso/login/authentication?token=
  token_url: http://service-sso/login


#注册中心地址，此部分配置无法刷新
eureka:
  client:
    serviceUrl:
      defaultZone: http://tu:8761/eureka
  healthcheck:
    enabled: true
    registry-fetch-interval-seconds: 10000 #间隔多久去拉取服务注册信息，默认为30秒

